# Detection adapter configuration for COCO DETR

MODEL:
  TYPE: "detr"
  NUM_CLASSES: 91  # COCO has 80 classes + background
  HIDDEN_DIM: 256
  NHEADS: 8
  NUM_ENCODER_LAYERS: 6
  NUM_DECODER_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: 0.1
  
DETECTION:
  SCORE_THRESHOLD: 0.25
  NMS_THRESHOLD: 0.5
  MAX_DETECTIONS: 100
  
INPUT:
  FEATURE_DIM: 1024  # DINOv3 ViT-L/16 feature dimension